Dev
Ashishgupta08/E-Commerce-App pull request #2
Opened 2021-05-06 17:41 UTC by Ashishgupta08

### E-Commerce App 
You can check the live demo of the app [here](https://100steps.netlify.app/)

Please give your valuable feedback for the enhancement of my project.
ThankYou!!!

2021-05-08 10:27 UTC, Akshay-Laxmipathi commented
Try adding the items to wishlist without having to redirect to the wishlist page everytime you click on the add to wishlist button.

2021-05-09 17:05 UTC, JatinRanka requested changes

2021-05-09 17:05 UTC, JatinRanka commented on src/Pages/Home.jsx
> +                    </NavLink>
Use cursor pointer

2021-05-09 17:05 UTC, JatinRanka commented on src/components/Nav/Nav.jsx
> +                    <li><NavLink to='/' className="link">
Add active class in nabber

2021-05-09 17:05 UTC, JatinRanka commented on src/Pages/Products.jsx
> +import { useWishlist } from "../Contexts/wishlist-context";
Use index file for import

2021-05-09 17:05 UTC, JatinRanka commented on src/Pages/Products.jsx
> +          return {productsList: state.productsList.sort((a,b)=>b.price.selling - a.price.selling)}
use snake case

2021-05-09 18:12 UTC, Ashishgupta08 commented on src/Pages/Home.jsx
> +                    </NavLink>
Done

2021-05-09 18:31 UTC, Ashishgupta08 commented on src/components/Nav/Nav.jsx
> +                    <li><NavLink to='/' className="link">
Done

2021-05-09 18:47 UTC, Ashishgupta08 commented on src/Pages/Products.jsx
> +import { useWishlist } from "../Contexts/wishlist-context";
Done

2021-05-09 18:50 UTC, Ashishgupta08 commented on src/Pages/Products.jsx
> +          return {productsList: state.productsList.sort((a,b)=>b.price.selling - a.price.selling)}
Done

2021-05-10 18:48 UTC, ishanjirety commented
The overall app looks amazing design is elegant there are some minimal points that must be considered 

- Must update the title of the application
- instead of console logging error, try adding user interaction eg. Toast, inline errors.
- avoid using short-forms in CSS classes eg. txt-1,txt-2, it is preferred to use heading sub-heading as it improves readability 
- Add 404 pages to handle unmatched routes.

Else everything looks good.

2021-06-28 10:15 UTC, closed without merging